version: "3.8"

services:
  backend:
    image: onealwaseem/todolist-backend:latest
    restart: always
    environment:
      - PORT=3082
      - CONNECTION_URL=mongodb+srv://GhonRequiem:12345678!@cluster0.fmepzut.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - REFRESH_TOKEN_SECRET=1234567890
      - ACCESS_TOKEN_SECRET=abcdefghijklmnop
      - EMAIL_USER=WADSWEEK12@gmail.com
      - EMAIL_PASS=ijar wmqt pqez osen
    ports:
      - "3082:3082"

  frontend:
    image: onealwaseem/todolist-frontend:latest
    restart: always
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3082
    ports:
      - "3081:3081"
